main.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall stunprober::StunProber::StunProber(class rtc::PacketSocketFactory *,class rtc::Thread *,class std::vector<class rtc::Network *,class std::allocator<class rtc::Network *> > const &)" (??0StunProber@stunprober@@QAE@PAVPacketSocketFactory@rtc@@PAVThread@3@ABV?$vector@PAVNetwork@rtc@@V?$allocator@PAVNetwork@rtc@@@std@@@std@@@Z)，该符号在函数 _main 中被引用
main.obj : error LNK2019: 无法解析的外部符号 "public: bool __thiscall stunprober::StunProber::Start(class std::vector<class rtc::SocketAddress,class std::allocator<class rtc::SocketAddress> > const &,bool,int,int,int,class rtc::Callback2<void,class stunprober::StunProber *,int>)" (?Start@StunProber@stunprober@@QAE_NABV?$vector@VSocketAddress@rtc@@V?$allocator@VSocketAddress@rtc@@@std@@@std@@_NHHHV?$Callback2@XPAVStunProber@stunprober@@H@rtc@@@Z)，该符号在函数 _main 中被引用
main.obj : error LNK2019: 无法解析的外部符号 "public: bool __thiscall stunprober::StunProber::GetStats(struct stunprober::StunProber::Stats *)const " (?GetStats@StunProber@stunprober@@QBE_NPAUStats@12@@Z)，该符号在函数 "void __cdecl `anonymous namespace'::PrintStats(class stunprober::StunProber *)" (?PrintStats@?A0xd12c6222@@YAXPAVStunProber@stunprober@@@Z) 中被引用
E:\project\webrtc\webrtc\git\webrtc_vs2015-master\webrtc_vs2015-master\vs140\Debug\stunserver.exe : fatal error LNK1120: 3 个无法解析的外部命令
